### ISSUE TITLE
Feedback  -  API  Eclipse (Teste 1)

### ISSUE THREAD

**Issue by alinebrito** [rodrigo-brito/RChess#1]
Hello,

We're interested in to study  Java APIs and libraries.  Your feedback helps guide our research. Please, answer our the question.

You used the API `org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser`  in `IOIParser` class. Did you know that is an unstable API of the Eclipse library?

File: xxx
Line: 123

**Comment by rodrigo-brito** [comment]
@alinebrito I don't used this API.
